spring.application.name=auth-service


server.port=9070
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb_safarsaathi

spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secretKey=mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.tags.application=${spring.application.name}
