spring.application.name=auth-service


server.port=9070
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb_safarsaathi

spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true


eurka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secretKey=mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890
