spring.application.name=notification-service

server.port=9080

spring.datasource.url=jdbc:postgresql://localhost:5432/safar_notificationdb
spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka