
FROM maven:3.9.8-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml .


RUN mvn dependency:go-offline


COPY src ./src


RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app


COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8761

ENTRYPOINT ["java","-jar","app.jar","--spring.profiles.active=docker"]