spring.application.name=companion-service

server.port=9040

# ==========================
# Database
# ==========================
spring.datasource.url=jdbc:postgresql://postgres:5432/safar_companiondb
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================
# Eureka
# ==========================
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=companion-service

# ==========================
# Management
# ==========================
management.health.neo4j.enabled=false

# ==========================
# Kafka
# ==========================
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer