spring.application.name=companion-service

server.port=9040


spring.datasource.url=jdbc:postgresql://postgres:5432/safar_companiondb
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=companion-service


management.health.neo4j.enabled=false

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.tags.application=${spring.application.name}


management.tracing.enabled=true

management.tracing.sampling.probability=1.0

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans