apiVersion: v1
kind: Service

metadata:
  name: companion-service
  namespace: safarsaathi

spec:
  selector:
    app: companion-service

  ports:
    - port: 9040
      targetPort: 9040

  type: ClusterIP