apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: safarsaathi

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service

          image: yash01er/safarsaathi-notification-service:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 9080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 20