apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: safarsaathi

spec:
  selector:
    app: notification-service

  ports:
    - port: 9080
      targetPort: 9080

  type: ClusterIP