apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: safarsaathi

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service

          image: yash01er/safarsaathi-user-service:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 9010

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 60
            periodSeconds: 20