apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: safarsaathi

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway

          image: yash01er/safarsaathi-api-gateway:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20