spring.application.name=user-service
server.port=9010

spring.datasource.url=jdbc:postgresql://localhost:5432/safar_userdb
spring.datasource.username=postgres
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.tags.application=${spring.application.name}