apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: safarsaathi

spec:
  storageClassName: gp2

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi